{% set name = "pegasus-wms.dax" %}
{% set version = "5.0.7" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63b1f16569698a00e4e3e100383e5e5a050030c6950246492d8ad21d6d7d31cd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - six >=1.9.0

test:
  requires:
    - pip
  imports:
    - Pegasus.DAX3
  commands:
    - python -m pip check

about:
  home: https://pegasus.isi.edu
  dev_url: https://github.com/pegasus-isi/pegasus.git
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pegasus Workflow Management System Python API
  description: |
    The `Pegasus.DAX3` API has been deprecated and will be removed in v5.1.0.
    Please use the new API released in v5.0.0.

extra:
  recipe-maintainers:
    - duncanmmacleod
